language: python
python:
  - "3.6"
dist: bionic
addons:
  snaps:
    - name: snapcraft
      confinement: classic
      channel: candidate
    - name: lxd
env:
  global:
    - LC_ALL=C.UTF-8
    - LANG=C.UTF-8

install:
  - sudo apt-get remove lxd-client lxc -y
  - sudo apt-get autoremove
  - sudo /snap/bin/lxd init --auto

script:
  # build with lxd because travis doesn't support focal yet, so we can't build
  # natively
  - sudo snapcraft --use-lxd
